### ISSUE TITLE
Bytes error in printed  output of `submit_dag`

### ISSUE THREAD

**Issue by GregoryAshton** [jrbourbeau/pycondor#118]
#### Description

When submitting a dag via `pycondor`, I get the following garbled output

```python
b'Submitting job(s).\n1 job(s) submitted to cluster 49593987.\n\n-----------------------------------------------------------------------\nFile for submitting this DAG to HTCondor           : GW150914/submit/main_GW150914_20181017_03.submit.condor.sub\nLog of DAGMan debugging messages                 : GW150914/submit/main_GW150914_20181017_03.submit.dagman.out\nLog of HTCondor library output                     : GW150914/submit/main_GW150914_20181017_03.submit.lib.out\nLog of HTCondor library error messages             : GW150914/submit/main_GW150914_20181017_03.submit.lib.err\nLog of the life of condor_dagman itself          : GW150914/submit/main_GW150914_20181017_03.submit.dagman.log\n\n-----------------------------------------------------------------------\n'
```

This is due to the `print(out)` statement where `out` is the first positional output from `submit_dag.communicate()`. 

This can be readily solved by something like
```
try:                                                                        
    out = out.decode('utf-8')                       
except AttributeError:                                                      
    pass
```
ensuring that if it is a bytes array, it is converted before calling `print(out)`. 

#### Extra info
Issue found on
Python version: 3.6 (anaconda-installed)
CondorVersion: 8.6.12 Jul 31 2018 BuildID: 446077
CondorPlatform: x86_64_RedHat7

Also, thanks for building this awesome tool. It is making my life a hell of a lot easier!

**Comment by jrbourbeau** [comment]
Thanks (again) for the great bug report @GregoryAshton. This issue should be fixed in #120

> Also, thanks for building this awesome tool. It is making my life a hell of a lot easier!

Thanks so much! Glad to hear there are others that find PyCondor useful
