### ISSUE TITLE
Windows require escaped backslash in submit files

### ISSUE THREAD

**Issue by khornlund** [jrbourbeau/pycondor#125]
#### Description
Windows requires backslashes in paths to be escaped, in order for them to be read correctly by HTCondor.

For example the contents of job.submit need to be:

```
log = condor\\log\\$(job_name).log
output = condor\\output\\$(job_name).output
error = condor\\error\\$(job_name).error
```

Due to use of os.path.join in Job and Dagman, the paths are printed to job.submit without being escaped.

This causes all of the error and output files to be transferred back to the submit machine at the root directory.

#### Suggestion:

It would be useful to have an optional param when calling build()/build_submit() which will escape all backslashes printed to submit/dag files.

Thoughts?

**Comment by jrbourbeau** [comment]
Thanks for opening up this issue @khornlund! Apologies for the delayed reply.

> It would be useful to have an optional param when calling build()/build_submit() which will escape all backslashes printed to submit/dag files

Generally I'd prefer not to add additional parameters if possible. Instead, preferring to take care of platform-specific steps automatically. For example, having something along the lines of

```python
if platform == 'windows':
    # Use escaped filepaths
else:
    # Use non-escaped paths
```

inside the `Job.build()` method. 

However, I did come across https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6747 in the HTCondor ticket tracker. It seems like what you're seeing could be related to this bug in HTCondor that was recently fixed.

**Comment by jrbourbeau** [comment]
That works, thanks for looking into if the new version of condor helps
