### ISSUE TITLE
execute a subdag if previous analysis steps generate correct output

### ISSUE THREAD

**Issue by simone-codeluppi** [jrbourbeau/pycondor#136]
Hi
thanks for creating pycondor. So far it has been extremely helpful in creating large scale processing graphs for my processing in HTCcondor.
I don't want to report a bug but ask you a question (If you cannot answer I can post it on Stackoverflow).  

__Problem__
I have created a DAG called A-dag and I want to chain to a second dag called B-dag. However, B-dag should be executed depending on the content of an output file generated from A-dag.

__Testing_solution__
- A-dag and B-dag works fine when tested independently and all the required file are provided
- I created a class that generate B-dag and when called return the dagman. In the class I check for the output file from A-dag
- In A-dag i first tried to import the class in order to directly create a subdag but as expected it execute the file check before it is created and breaks. So this approach is not working.
- In A-dag I created a job that execute the B-dag script. However I cannot add it as subdag or job.

__Question__
What is the standard way to deal with DAG that need to be executed depending on the output of a previous DAG?

Any help is really appreciated
Simone

**Comment by jrbourbeau** [comment]
Glad to hear PyCondor has been useful for you @simone-codeluppi! 

Based on the information you've provided, perhaps adding both A-dag and B-dag as subdags to another dag that will manage the entire workflow could help here. Then you could make A-dag a parent of B-dag, which will ensure that A-dag finishes before B-dag is run. Something like:

```python
from pycondor import Dagman

# Create a dag to manage the entire workflow
dag_total = Dagman(...)

# Add dag_a and dag_b as subdags to dag_total
dag_a = Dagman(..., dag=dag_total)
dag_b = Dagman(..., dag=dag_total)

# Make sure dag_a finishes before dag_b starts
dag_b.add_parent(dag_a)

# Build and submit workflow
dag_total.build_submit()
```

**Comment by simone-codeluppi** [comment]
Thanks for the reply! I will test it and get back to you!

**Comment by simone-codeluppi** [comment]
Great! It works! thanks for the help!
