### ISSUE TITLE
HTCondor python bindings

### ISSUE THREAD

**Issue by kreczko** [jrbourbeau/pycondor#35]
Since `pip install htcondor` is now possible (in addition to `conda install htcondor-python` and python 3 support is coming soon, it probably would make sense to use the bindings provided by the HTCondor team.

Using them should be easier, safer and faster than using & parsing the command line:
https://indico.cern.ch/event/611296/contributions/2604395/attachments/1472564/2279252/Bockelman-European-HTCondorWeek-Python-2017_.pdf

What do you think?

**Comment by jrbourbeau** [comment]
Hey @kreczko, thanks for the comment! In theory I totally agree that the official Python bindings from the HTCondor team are probably a better way to go. 

I looked through the [documentation for the bindings](https://htcondor-python.readthedocs.io/en/latest/) and really liked the syntax for instantiating a `htcondor.Submit` object with a dictionary. That could easily be utilized in PyCondor. 

One concern I have is that there was only a single reference to dagman in the documentation. Do the bindings have support for creating some kind of dagman submit object?

**Comment by kreczko** [comment]
Hi @jrbourbeau If you look at this weeks slides for ["What's New in HTCondor?", slide 18](https://indico.cern.ch/event/611296/contributions/2604396/attachments/1472714/2279525/TannenbaumT_WhatsNew.pdf) you can see that they are investigating integration with [Dask](http://dask.pydata.org/en/latest/). I've also attempted to add an HTCondor Luigi Task before but was held back by the lack of easy install for the python bindings (fixed this week :)).

Both solutions make more sense than direct dagman since it is lacking in places. It's likely the reason for your project. We had a similar project in our group: [htcondenser](https://github.com/raggleton/htcondenser).

I do not know the scope or timeframe of your project, but at least I wanted to let you know that things are improving and the developers are listening. It is probably worth expressing interest in the creation of HTCondor DAGs in python. I would not be surprised if they see it as a sign to put more work into this.

That said, it seems they already have a (working?) version:
https://github.com/matyasselmeci/dask_condor/blob/master/dask_condor/__init__.py

**Comment by jrbourbeau** [comment]
Thanks for all of the information! I'm glad to hear about integration with Dask and python 3 support. Do you know how I might go about voicing my interest for a dag object in the python bindings?

**Comment by kreczko** [comment]
I think the best way would be the htcondor-users list: htcondor-users@cs.wisc.edu (see https://research.cs.wisc.edu/htcondor/mail-lists/) as the issues are disabled on https://github.com/htcondor/htcondor.

If your profile is still correct, you could also just visit the HTCondor developers in the computer science department ;).

**Comment by bbockelm** [comment]
Hi,

(Apologies, I was at a conference all last week)

Currently, the official python bindings have focused on exposing objects/concepts in the HTCondor libraries to python.  So, there's a really thorough treating of things like ClassAds or the (new-ish) Submit object.

However, HTCondor doesn't really have a library version of DAGMan file parsing -- but they could create one!

My hope was that we could have a merge of the two libraries a bit: take the existing DAGMan object in pycondor and move it into the official ones.  This way, we could perhaps have more efficient submit / job tracking but also better coverage of workflows.

In the meantime, I'll chat with the condor team and see if they would want to refactor DAGMan to have a library interface we could plug into.  I'm not entirely sure there is good code in condor to _write_ DAGs (after all, I don't think anything in condor does this internally!) but there at least ought to be official code for generating them.

HTH,

Brian

**Comment by jrbourbeau** [comment]
Hey @bbockelm,

Having some DAGMan functionality in official Python bindings would be great! As you mentioned, adding a dagman object would be a natural extension to include better coverage of workflows. 

> My hope was that we could have a merge of the two libraries a bit: take the existing DAGMan object in pycondor and move it into the official ones. 

If there's anything I can do to help facilitate this, just let me know!

**Comment by bbockelm** [comment]
Would it be possible to try to do a lift of the DAGMan object itself as a PR to htcondor?  Or is that not the right way to break down the work?

(I unfortunately am not sure I have much time to work on it, but I like the idea...)

**Comment by jrbourbeau** [comment]
@bbockelm sorry for such a delayed response! 

I'm not sure that the `pycondor.Dagman` object in this project could be lifted into the `htcondor` pybindings in its current state. Unfortunately, I'm not familiar with the Python bindings internals and don't have a lot of spare time at the moment. But perhaps in the future, I can work on re-factoring PyCondor to be implemented in terms of the `htcondor` Python bindings. 

Again, apologies for taking forever to get back to you.

**Comment by jrbourbeau** [comment]
I'm going to close this issue, but we can feel free to keep this conversation going here.
