### ISSUE TITLE
Number for error/log/output files starts at 02

### ISSUE THREAD

**Issue by ljwille** [jrbourbeau/pycondor#47]
#### Description

Naming scheme for job output files inconsistent with submit files.

#### Steps/code to reproduce issue
import pycondor

error = "/home/error"
output = '/home/output'
log = '/home/log'
submit = '/home/submit'

job = pycondor.Job('test', '/home/test.py', error=error, output=output, log=log, submit=submit, verbose=2)

dagman = pycondor.Dagman('tauMaster_dagman', submit=submit)
dagman.add_job(job)

for i in range(0,10):   
    job.add_arg(' -i ' + i, name = str(i))

dagman.build_submit()

#### Expected results

Files in the output/log/error folders to be named test_DATE_01_NAME to match the submit files in the submit folders

#### Actual results

Files in the output/log/error folders are named test_DATE_02_NAME

**Comment by jrbourbeau** [comment]
Thanks for reporting this @ljwille! I was able to reproduce the submit vs. log/error/output filename mismatch. I'll work on a fix.
