### ISSUE TITLE
dagman Rescue file not using unique job names

### ISSUE THREAD

**Issue by ljwille** [jrbourbeau/pycondor#49]
#### Description

The rescue file created by the unique name from add_arg and instead uses the generic name such as JOBNAME_arg_###.

#### Steps/code to reproduce issue
import pycondor

# Declare the error, output, log, and submit directories for Condor Job
error = 'condor/error'
output = 'condor/output'
log = 'condor/log'
submit = 'condor/submit'

# Setting up a PyCondor Job
job = pycondor.Job('examplejob', 'savelist.py',
               error=error, output=output,
               log=log, submit=submit, verbose=2)
# Adding arguments to job
job.add_arg('--length 50', name = '50')
job.add_arg('--length 100', name ='100')
job.add_arg('--length 200', name = '200')

# Setting up a PyCondor Dagman
dagman = pycondor.Dagman('exampledagman', submit=submit, verbose=2)
# Add job to dagman
dagman.add_job(job)
# Write all necessary submit files and submit job to Condor
dagman.build_submit()

Where example script will fail so as to create a rescue file.

#### Expected results

Names in the rescue file to be 'examplejob_50', 'examplejob_100', 'examplejob_200'.

#### Actual results

Names in the rescue file are 'examplejob_arg_00', 'examplejob_arg_01', 'examplejob_arg_02''.

**Comment by jrbourbeau** [comment]
@ljwille thanks for submitting this issue. It definitely makes sense to use the argument name in the node name (so the argument name will appear in any generated rescue files). I can work on implementing this.
