### ISSUE TITLE
Add safeguard to prevent job name error in newer versions of condor

### ISSUE THREAD

**Issue by tianluyuan** [jrbourbeau/pycondor#63]
#### Description

In condor version `8.7.5` dagman submission fails if the job name has `+` or `.` in it. This error will lead to a silent failure with the submission, so it'd be better to add a safeguard in `pycondor` by raising a `RuntimeError` or something similar

**Comment by jrbourbeau** [comment]
Thanks for the issue @tianluyuan! It looks like `+` and `.` characters became prohibited in version `8.7.2` (see the [release notes](http://research.cs.wisc.edu/htcondor/manual/v8.7/11_2Development_Release.html)).

> add a safeguard in pycondor by raising a RuntimeError or something similar

 I think that sounds totally reasonable
