### ISSUE TITLE
Add click to the test requirements file.

### ISSUE THREAD

**Issue by zdgriffith** [jrbourbeau/pycondor#86]
#### Description

Click is required to run the tests, but not in the requirements file.  It should be added.

#### Actual results

~~~~
ImportError while importing test module '/home/zgriffith/pycondor/pycondor/tests/test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
pycondor/tests/test_cli.py:5: in <module>
    from click.testing import CliRunner
E   ModuleNotFoundError: No module named 'click'
~~~~

**Comment by jrbourbeau** [comment]
Thanks for the issue report @zdgriffith. `click` is included in the default `pycondor` requirements file (`requirements/default.txt`) and will be installed whenever `pycondor` is installed. 

It looks like I forgot to add a step in the contributing guide where your local copy is actually installed! I'll go ahead and add that now. Thanks!
